env:
  RENDER_VERSION: v0.0.37
  ECR_VERSION: v2.7.0
  AWS_REGION: us-east-1
  ACCOUNT_ID: '018537234677'
  SLACK_CHANNEL: '#eng-eti-deploy'

#####################################################################
############## Build, lint and test #################################
#####################################################################

steps:
  - label: ':announcement: Deployment started'
    if: build.branch == pipeline.default_branch
    key: start-gate
    command: 'true'
    concurrency: 1
    concurrency_group: 'twilio-mcp/deploy'
    notify:
      - slack:
          channels:
            - ${SLACK_CHANNEL}
          message: |
            Starting deployment :shipitparrot:
            Commit Message: ${BUILDKITE_MESSAGE}
            cc: @${PR_AUTHOR_EMAIL}

  - label: ':npm: Build package'
    key: build
    id: build
    command:
      - npm ci
      - npm run build
    env:
      CI: true
      NODE_ENV: test
    plugins:
      - docker#v3.7.0:
          image: 'node:20'
          environment:
            - CI

  - label: ':npm: Run Lint'
    key: lint
    id: lint
    command:
      - npm ci
      - npm run lint
    env:
      CI: true
      NODE_ENV: test
    plugins:
      - docker#v3.7.0:
          image: 'node:20'
          environment:
            - CI

  - label: ':npm: Run Tests'
    key: unit-testing
    command:
      - npm ci
      - npm test
    env:
      CI: true
      NODE_ENV: test
    plugins:
      - docker#v3.7.0:
          image: 'node:20'
          environment:
            - CI

  #####################################################################
  ############## Publish Package ######################################
  #####################################################################

  - wait: ~
    if: build.branch == pipeline.default_branch

  - label: ':npm: Publish packages to NPM?'
    if: build.branch == pipeline.default_branch
    concurrency: 1
    concurrency_group: 'twilio-mcp/deploy'
    command: |
      if [ $$(buildkite-agent step get "outcome" --step "lint") == "passed" ] && [ $$(buildkite-agent step get "outcome" --step "build") == "passed" ]; then
        cat <<- YAML | buildkite-agent pipeline upload
        steps:
          - block: ':npm: Publish packages to NPM?'
            if: build.branch == pipeline.default_branch
            key: block-publish
            depends_on:
              - build
              - lint
      YAML
      fi

  - label: ':npm: Publishing to NPM'
    if: build.branch == pipeline.default_branch && env("RELEASE_NPM") == "true"
    key: deploy-prod-use1
    concurrency: 1
    concurrency_group: 'twilio-mcp/deploy'
    depends_on:
      - block-publish
      - build
      - lint
    plugins:
      - docker#v3.7.0:
          image: 'node:20'
          environment:
            - CI
    commands: |
      npm ci
      npm run build
      git config --global user.name 'Twilio ETI Bot'
      git config --global user.email 'eti@twilio.com'
      npm config set //registry.npmjs.org/:_authToken ${TWILIO_NPMJS_PUBLISH_TOKEN}
      npm publish -w @twilio-alpha/mcp
    notify:
      - slack:
          channels:
            - ${SLACK_CHANNEL}
          message: |
            Published package
            Commit Message: ${BUILDKITE_MESSAGE}
            cc: @${PR_AUTHOR_EMAIL}
