#!/bin/bash
set -euo pipefail

export TWILIO_NPMJS_PUBLISH_TOKEN=$(aws s3 cp s3://com-twilio-corp-us1-secrets/v1/buildkite-build-worker/jobs_eti_npmPublishToken/latest -)

# Github userId to twilio email mapping
declare -A email_map=(
    ["kousha"]="ktalebian@twilio.com"
    ["talebian"]="ktalebian@twilio.com"
    ["vinnie"]="vgiarrusso@twilio.com"
    ["giarrusso"]="vgiarrusso@twilio.com"
    ["brian"]="bpartridge@twilio.com"
    ["partridge"]="bpartridge@twilio.com"
)

# Function to get mapped email
get_mapped_email() {
    local email_string="$1"
    for key in "${!email_map[@]}"; do
        if [[ "$email_string" == *"$key"* ]]; then
            echo "${email_map[$key]}"
            return
        fi
    done
    # By default return the original email string
    echo $email_string
}

export PR_AUTHOR_EMAIL=$(get_mapped_email "${BUILDKITE_BUILD_AUTHOR_EMAIL}")